### ISSUE TITLE
Support registration of partial images

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/amap-python#1]
Allow registration of subvolumes via masking.

**Comment by adamltyson** [comment]
There is also a lot of interest in registration of single planes to the 3D atlas. Not sure if this should be in amap, or in a separate package.

**Comment by paulbrodersen** [comment]
Hi Adam

I would be interested in both of these features, and would be happy to contribute. 

In my use case, I have several image series of serial coronal dissections of a single hemisphere (with very sparsely fluorescently labelled cells). However, the series are incomplete, i.e. they contain only a few slices of each brain. I saw in the very readable source code that there appears to be already some support for registration of hemispheres.  

I wondered if you could find the time to discuss a roadmap of what work would need to be done in this direction -- either here in the issue itself or via skype/zoom/hangouts if that is easier for you. 

Best, Paul

**Comment by adamltyson** [comment]
Hi Paul,

That sounds great, maybe send me an email on `adam.tyson@ucl.ac.uk` and we can find a time?

Best,
Adam

**Comment by vigji** [comment]
I need to register a single hemisphere, although in my case I have the full volume and not sparse planes, so some masking on the reference could potentially be enough. I would be interested to know about any updates @paulbrodersen!

**Comment by paulbrodersen** [comment]
@adamltyson has started working on [slicereg](https://github.com/adamltyson/slicereg), and I hope to join him this week or the next on that project. The repository is designed to register individual slices to a 3D volume reference. I don't think this will be relevant for your case. 

From my perusing the code base of amap, it looked to me like there was some support for registering hemispheres already but @adamltyson will be much more qualified to answer that question.

**Comment by adamltyson** [comment]
Hi both.

I don't think the hemisphere registration is what you're after. This is just applying the same transform that is applied to the atlas annotations to a custom hemisphere atlas (literally just a value of 1 on one side, and 2 on the other) to ensure that laterality is taken into account (because e.g. the Allen atlas is symmetrical). 

That being said, masking should be pretty straightforward, I've just never got round to it. I'm pretty busy at the moment, but if anybody fancies having a go, I'm happy to help and show you around as it were.

**Comment by vigji** [comment]
I have finally be able to test this. First thing I did for a quick fix was just creating a new atlas cropping one hemisphere, and running aMAP python normally on the new atlas (masking one side of the atlas works as well, but gave a worse result because re registration seems to try squeezing the empty half of the stack in the stack space where I have only the hemisphere).

This could be one solution - just having a separate atlas for the 1 hemisphere registration - but obviously would be quite suboptimal, duplicating data for no reason. I am now trying to have this as an argument that can be passed to the registration. I would add this as argument to the `Atlas` class and add a method to cut the `_data` stack.
Let me know if you have other suggestions - I will open a PR for this as soon as possible :)

**Comment by adamltyson** [comment]
Cool. The atlas data is already processed quite a bit anyway (flips & orientation changes, I'm also in the process of allowing arbitrary rotations). It would be great to have command line options for arbitrary cropping of the atlas (so any brain subvolume could theoretically be processed), but registering a single hemisphere would be a good default (e.g. `--hemisphere left` or `--hemisphere right`).

Another thing to think about is what the output will be. It's important for other software to not just overlay atlas boundaries onto raw (or downsampled raw) data, but to be able to inverse the transform and get detected features from the sample data space into atlas space. I'm not sure how to deal with this. Your result suggests we can't register a subvolume to a masked atlas (which is to be expected), so we could:
1. Register subvolume to cropped atlas (i.e. make the atlas image smaller), and somehow record the portion of the atlas used to bring data back into the full atlas space later on
2. Register subvolume to cropped atlas, but then store the results as if they were from a full-brain space (keep a full size atlas image, and pad the raw data)
3. Pad the raw data at the beginning, and try registration to a masked atlas.

Any ideas? 1 and 2 would speed up registration (and reduce RAM usage), and 1 would save on disk space, but require more work downstream for other software. 3 is conceptually simple, at the expense of disk space, RAM usage and processing time. It would be interesting to look at the registration results of the different options. We have lots of whole-brain datasets, so we could do some ground truth (whole-brain registration) comparisons.

P.S as you may have noticed, there are a lot of imports from other packages of mine (e.g. `neuro`, `imlib`, `slumrio`, `brainio`, `micrometa` & `fancylog`). These are not necessarily organised in the most optimal way at the moment, and so are changing rapidly. Let me know if you have any issues, and I'll try to ensure that only fully working code is in the master branch.

**Comment by vigji** [comment]
Hi adam, I am reading through the library right now and I noticed and wanted to ask about that - I am just working in an environment and it would be easy to pull whathever update when you release them!

For the atlas-to-image-transformation, I guess we don't care at all. For the image-to-atlas transformation, taking care of the cropping should be just adding the offsets of the cropping to the inverse affine transformation - will for sure cause some headaches, but should not be hard hand for sure the efficiency gain would be worth it 

I already tested 3. and it works as well as the cropped-to-cropped registration, but yeah, huge waste of space and time.

On a side note, to improve efficiency: I noticed that when you load/transform/save the atlas stacks you don't do this sequentially: I wanted to try to change that to do the operations sequentially, file by file, to avoid having to keep everything in memory - does it make sense?

**Comment by adamltyson** [comment]
I'm currently releasing all the new versions, and update requirements in amap. Should all be done soon (it's a slow process, they only release once the tests pass, which requires their dependencies to already have been released). I'll let you know when it's all done.

Good to know that the registration is ok with the different options. I also think 1 is good. Ideally I'd like people to be able to register very small volumes (say a cubic mm), and requiring 25GB of RAM for that is a bit stupid. I'll have a think of how best to deal with it in other software (namely neuro & cellfinder), but there also are amap users that would like automatic sample-> atlas registration as an option.

Your last point is linked to https://github.com/SainsburyWellcomeCentre/amap-python/issues/42. As far as I see it, there's no reason why preprocessing should use any more memory than a single image. I think it's just the way it is for historical reasons. If you could fix that, it would be awesome.

**Comment by adamltyson** [comment]
All new versions are released, and the amap master branch should be fine to work from.

**Comment by adamltyson** [comment]
Moved to https://github.com/brainglobe/brainreg/issues/6
