### ISSUE TITLE
Affine results visualisation

### ISSUE THREAD

**Issue by FedeClaudi** [SainsburyWellcomeCentre/amap-python#7]
I think it kind of makes sense to have a simple way to visualize the results of running amap on some data built into amap itself. 

I'm happy to write something to just display the allen reference brain and the input data overlaid, but wanted to check that I'm not missing something that is already there/ you're not planning to do it yourself any time soon.

**Comment by adamltyson** [comment]
I was planning on adding this fairly soon (I've got all the code in other projects). Maybe you can let me know how this sounds:
* A command line flag (e.g. `--vis`) which will precompute the region outlines (similar to attached image).
* A separate command (e.g. `amap-vis`) which will launch napari to show the downsampled image, atlas annotations (coloured), and the region outlines. These can then be toggled, zoomed etc.

![overlay](https://user-images.githubusercontent.com/13147259/70741240-c205d380-1d12-11ea-95e6-5ac331ce8990.png)

**Comment by adamltyson** [comment]
Actually - looking a bit more like this. 
![annotations_overlay](https://user-images.githubusercontent.com/13147259/70741579-81f32080-1d13-11ea-8bd9-837b19f6909c.png)

**Comment by FedeClaudi** [comment]
The image is awesome, that would be ideal. Running it either directly when running amap on the data (with the flag) or after it's completed with a separate command, works. Probably best to have the option to do both. 

Would it be possible to have it so that you can scroll through the whole brain to check the alignment at multiple points? Or maybe to show/save figure like this for a subset of slices along the brain. 

The second one might be a bit harder to see? maybe make the overlay more transparent..

**Comment by adamltyson** [comment]
Yep, it will be the full stack, so you can scroll (and view in arbitrary orientations).
Each channel (downsampled, annotations and outlines) can be turned off, and transparency changed.

**Comment by FedeClaudi** [comment]
That sounds awesome, looking forward to it!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by adamltyson** [comment]
This is what it looks like so far. The scaling is off because I'm using a 4K monitor ([known napari issue](https://github.com/napari/napari/issues/367)).

Next steps are: 
* Optional loading of different images (transformed average brain, hemispheres etc)
* Virtual loading of the full-size image stack.

Any thoughts @FedeClaudi ?
![amap_viewer](https://user-images.githubusercontent.com/13147259/70794875-962c3180-1d96-11ea-8941-b74809955bf6.gif)

**Comment by FedeClaudi** [comment]
That's awesome!!!

**Comment by adamltyson** [comment]
Very early stages, but if you want to use this to look at your data, you can install the alpha version with `pip install amap==0.0.10a1`.

Then rerun `amap`, it should detect what has been run previously, then just generate the outlines. 

Then run `amap_vis /path/to/your/amap/output/directory`, and the viewer should pop up.

**Comment by adamltyson** [comment]
Closing this as the viewer now exists. If bugs remain, they can be in a separate issue.
